export const imageLinks = {
    BTC: 'https://reoncoin.io/crypto/btc.png',
    ETH: 'https://reoncoin.io/crypto/eth.png',
    XRP: 'https://reoncoin.io/crypto/xrp.png',
    BCH: 'https://reoncoin.io/crypto/bch.png',
    LTC: 'https://reoncoin.io/crypto/ltc.png',
    DASH:'https://reoncoin.io/crypto/dash.png',
    XEM: 'https://reoncoin.io/crypto/xem.png',
    BCC: 'https://reoncoin.io/crypto/bcc.png',
    XMR: 'https://reoncoin.io/crypto/xmr.png',
    NEO: 'https://reoncoin.io/crypto/neo.png',
    MIOTA: 'https://reoncoin.io/crypto/miota.png',
    ADA: 'https://reoncoin.io/crypto/ada.png',
    BTG: 'https://reoncoin.io/crypto/btg.png',
    XLM: 'https://reoncoin.io/crypto/xlm.png',
    ADA: 'https://reoncoin.io/crypto/ada.png',
    TRX: 'https://reoncoin.io/crypto/trx.png',
    EOS: 'https://reoncoin.io/crypto/eos.png',
    BNB: 'https://reoncoin.io/crypto/bnb.png',
    USDT:'https://reoncoin.io/crypto/usdt.png',
    BSV: 'https://reoncoin.io/crypto/bsv.png',
    ABT: 'https://reoncoin.io/crypto/abt.png',
    ACT: 'https://reoncoin.io/crypto/act.png',
    ACTN: 'https://reoncoin.io/crypto/actn.png',
    ADD: 'https://reoncoin.io/crypto/add.png',
    ADX: 'https://reoncoin.io/crypto/adx.png',
    AEON: 'https://reoncoin.io/crypto/aeon.png',
    AE: 'https://reoncoin.io/crypto/ae.png',
    
}